# Generated by Django 4.0.3 on 2022-08-13 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_count', models.IntegerField(default=1)),
                ('true_answers', models.IntegerField(default=0)),
                ('count_questions', models.IntegerField(default=0)),
                ('start', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('time_start', models.DateTimeField(null=True)),
                ('time_finish', models.DateTimeField(null=True)),
                ('list_questions', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User_statistik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt', models.IntegerField(default=0)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_work.list_tests')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt', models.IntegerField()),
                ('id_number', models.IntegerField()),
                ('answer', models.JSONField()),
                ('comment', models.TextField(null=True)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_work.list_tests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic_answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_do_test.attempts')),
            ],
        ),
        migrations.AddField(
            model_name='attempts',
            name='id_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_do_test.user_statistik'),
        ),
        migrations.AddField(
            model_name='attempts',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
