# Generated by Django 4.0.3 on 2022-10-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_do_test', '0007_alter_attempts_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='step_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
